handi_a_dit/urls.py
from django.contrib import admin
from django.urls import include, path

from quiz import views

urlpatterns = [
        path('', views.index),
        path('quiz/', include('quiz.urls')),
    path('admin/', admin.site.urls),
]

quiz/urls.py
from django.urls import path

from quiz import views

app_name = "quiz"
urlpatterns = [
        path('', views.index, name='index'),
        path('<int:question_id>/', views.detail, name='detail'),
        path('<int:question_id>/results/', views.results, name='results'),
        path('<int:question_id>/vote/', views.vote, name='vote'),
        ]

quiz/models.py
from django.db import models

class AuthoringDatesModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Question(AuthoringDatesModel):
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return self.question_text

class Choice(AuthoringDatesModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

quiz/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render

from quiz.models import Question

def index(request):
    latest_question_list = Question.objects.order_by('-created_at')[:5]
    context = {
        'latest_question_list': latest_question_list,
        }
    return render(request, 'quiz/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Oh mince... Ce quiz n'existe pas !")
    return render(request, 'quiz/detail.html', {"question": question})

def results(request, question_id):
    return HttpResponse(f"Vous regardez les résultats de la question {question_id}")

def vote(request, question_id):
    return HttpResponse(f"Vous répondez à la question {question_id}")

quiz/templates/base.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Handi a dit</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

quiz/templates/quiz/detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Handi a dit</h1>
    <p>Bienvenue sur la page d'accueil du site Handi a dit !</p>

    <h2>{{ question.question_text }}</h2>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
        {% endfor %}
    </ul>
{% endblock %}

quiz/templates/quiz/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Handi a dit</h1>
    <p>Bienvenue sur la page d'accueil du site Handi a dit !</p>

    <h2>Derniers quiz</h2>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'quiz:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Aucun quiz disponible.</p>
    {% endif %}
{% endblock %}